version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # volumes:
    #   - ./data:/app/data
